import random
from art import logo

# GLOBAL RANDOM GENERATED BY COMPUTER WE WILL NOT CHANGE THIS WITHIN OUR CODE SO THAT IS WHY WE REPRESENT THE NAME OF THE VARIABLE USING CAPITALS
NUMBER_GENERATED = random.randint(1, 100)
# print(NUMBER_GENERATED)

def guess_the_number(number_of_attempts):

    for i in range(0 , number_of_attempts):

        print(f"You have {number_of_attempts - i} attempts remaining to guess the number.")
        user_guess = int(input("Make a guess: "))

        if(user_guess == NUMBER_GENERATED):
            return True
        
        elif(user_guess > NUMBER_GENERATED):
            print(f"Too high.\nGuess again.")

        elif(user_guess < NUMBER_GENERATED):
            print(f"Too low.\nGuess again.")
    
    # If number of attempt completed and not guessed correct return False
    return False

difficulty_level = {"easy" : 10 , "hard" : 5}


print(logo)
print("Welcome to the Number Guessing Game!")
print("I'm thinking of a number between 1 and 100.")

user_selected_difficulty_level = input("Choose a difficulty. Type 'easy' or 'hard': ").lower()

isCorrectelyGuessed = guess_the_number(difficulty_level[user_selected_difficulty_level])

if isCorrectelyGuessed:
    print(f"You got it! The answer was {NUMBER_GENERATED}")
else:
    print(f"You've run out of guesses, you lose.\nThe answer was {NUMBER_GENERATED}")